version: '3.8'
services:
  
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/data:/usr/share/nginx/html
  
  next:
    build:
      context: ./next
  
  ssl-proxy:
    build:
      context: ./ssl-proxy
    ports:
    - '80:80'
    - '443:443'    



