version: '3.8'
services:
  
  nginx:
    build:
      context: ./nginx
    restart: always
  
  next:
    build:
      context: ./next
    restart: always

  ssl-proxy:
    build:
      context: ./ssl-proxy
    restart: always
    ports:
      - '80:80'
      - '443:4430'    
